version: '3'
services:
    web:
        image: aula-ws-web
        build: .
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        ports:
            - 80:80
        env_file:
            - .env
        command: npm start
volumes:
    node_modules: