version: '3'
services:
    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - 127.0.0.1:3306:3306
    api-node:
        build: ./node
        volumes:
            - ./node:/app
            - node_modules:/app/node_modules
        ports:
            - 8080:80
        env_file:
            - .env
        command: npm start
    api-php:
        build: ./php
        volumes:
            - ./php:/var/www/html
        ports:
            - '8081:80'
    nginx:
        image: valian/docker-nginx-auto-ssl
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        environment:
            - SITES=node.${URL}=api-node;php.${URL}=api-php
            - FORCE_HTTPS=true
volumes:
    node_modules:
    mysql: